// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "food_log.proto" (package "proto", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * 食事記録の作成リクエスト
 *
 * @generated from protobuf message proto.CreateFoodLogRequest
 */
export interface CreateFoodLogRequest {
    /**
     * @generated from protobuf field: int32 user_id = 1
     */
    userId: number;
    /**
     * @generated from protobuf field: string date = 2
     */
    date: string; // YYYY-MM-DD format
    /**
     * @generated from protobuf field: string diary = 3
     */
    diary: string; // 300文字制限
    /**
     * @generated from protobuf field: repeated string photos = 4
     */
    photos: string[]; // 最大3枚
    /**
     * @generated from protobuf field: bool is_public = 5
     */
    isPublic: boolean;
}
/**
 * 食事記録の作成レスポンス
 *
 * @generated from protobuf message proto.CreateFoodLogResponse
 */
export interface CreateFoodLogResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: proto.FoodLog record = 3
     */
    record?: FoodLog;
}
/**
 * 食事記録の取得リクエスト
 *
 * @generated from protobuf message proto.GetFoodLogRequest
 */
export interface GetFoodLogRequest {
    /**
     * @generated from protobuf field: int32 user_id = 1
     */
    userId: number;
    /**
     * @generated from protobuf field: string date = 2
     */
    date: string; // YYYY-MM-DD format
}
/**
 * 食事記録の取得レスポンス
 *
 * @generated from protobuf message proto.GetFoodLogResponse
 */
export interface GetFoodLogResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: proto.FoodLog record = 3
     */
    record?: FoodLog;
}
/**
 * 複数の食事記録の取得リクエスト
 *
 * @generated from protobuf message proto.GetFoodLogsRequest
 */
export interface GetFoodLogsRequest {
    /**
     * @generated from protobuf field: int32 user_id = 1
     */
    userId: number;
    /**
     * @generated from protobuf field: string start_date = 2
     */
    startDate: string; // Optional: YYYY-MM-DD format
    /**
     * @generated from protobuf field: string end_date = 3
     */
    endDate: string; // Optional: YYYY-MM-DD format
}
/**
 * 複数の食事記録の取得レスポンス
 *
 * @generated from protobuf message proto.GetFoodLogsResponse
 */
export interface GetFoodLogsResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: repeated proto.FoodLog records = 3
     */
    records: FoodLog[];
}
/**
 * 記録済み日付取得リクエスト
 *
 * @generated from protobuf message proto.GetFoodLogDatesRequest
 */
export interface GetFoodLogDatesRequest {
    /**
     * @generated from protobuf field: int32 user_id = 1
     */
    userId: number;
    /**
     * @generated from protobuf field: int32 year = 2
     */
    year: number;
    /**
     * @generated from protobuf field: int32 month = 3
     */
    month: number;
}
/**
 * 記録済み日付取得レスポンス
 *
 * @generated from protobuf message proto.GetFoodLogDatesResponse
 */
export interface GetFoodLogDatesResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: repeated int32 recorded_days = 3
     */
    recordedDays: number[];
}
/**
 * 食事記録モデル
 *
 * @generated from protobuf message proto.FoodLog
 */
export interface FoodLog {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: int32 user_id = 2
     */
    userId: number;
    /**
     * @generated from protobuf field: string date = 3
     */
    date: string; // YYYY-MM-DD format
    /**
     * @generated from protobuf field: string diary = 4
     */
    diary: string;
    /**
     * @generated from protobuf field: repeated string photos = 5
     */
    photos: string[];
    /**
     * @generated from protobuf field: bool is_public = 6
     */
    isPublic: boolean;
    /**
     * @generated from protobuf field: string created_at = 7
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string updated_at = 8
     */
    updatedAt: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateFoodLogRequest$Type extends MessageType<CreateFoodLogRequest> {
    constructor() {
        super("proto.CreateFoodLogRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "diary", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "photos", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "is_public", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<CreateFoodLogRequest>): CreateFoodLogRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = 0;
        message.date = "";
        message.diary = "";
        message.photos = [];
        message.isPublic = false;
        if (value !== undefined)
            reflectionMergePartial<CreateFoodLogRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateFoodLogRequest): CreateFoodLogRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 user_id */ 1:
                    message.userId = reader.int32();
                    break;
                case /* string date */ 2:
                    message.date = reader.string();
                    break;
                case /* string diary */ 3:
                    message.diary = reader.string();
                    break;
                case /* repeated string photos */ 4:
                    message.photos.push(reader.string());
                    break;
                case /* bool is_public */ 5:
                    message.isPublic = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateFoodLogRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 user_id = 1; */
        if (message.userId !== 0)
            writer.tag(1, WireType.Varint).int32(message.userId);
        /* string date = 2; */
        if (message.date !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.date);
        /* string diary = 3; */
        if (message.diary !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.diary);
        /* repeated string photos = 4; */
        for (let i = 0; i < message.photos.length; i++)
            writer.tag(4, WireType.LengthDelimited).string(message.photos[i]);
        /* bool is_public = 5; */
        if (message.isPublic !== false)
            writer.tag(5, WireType.Varint).bool(message.isPublic);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.CreateFoodLogRequest
 */
export const CreateFoodLogRequest = new CreateFoodLogRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateFoodLogResponse$Type extends MessageType<CreateFoodLogResponse> {
    constructor() {
        super("proto.CreateFoodLogResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "record", kind: "message", T: () => FoodLog }
        ]);
    }
    create(value?: PartialMessage<CreateFoodLogResponse>): CreateFoodLogResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<CreateFoodLogResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateFoodLogResponse): CreateFoodLogResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* proto.FoodLog record */ 3:
                    message.record = FoodLog.internalBinaryRead(reader, reader.uint32(), options, message.record);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateFoodLogResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* proto.FoodLog record = 3; */
        if (message.record)
            FoodLog.internalBinaryWrite(message.record, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.CreateFoodLogResponse
 */
export const CreateFoodLogResponse = new CreateFoodLogResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetFoodLogRequest$Type extends MessageType<GetFoodLogRequest> {
    constructor() {
        super("proto.GetFoodLogRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "date", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetFoodLogRequest>): GetFoodLogRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = 0;
        message.date = "";
        if (value !== undefined)
            reflectionMergePartial<GetFoodLogRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetFoodLogRequest): GetFoodLogRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 user_id */ 1:
                    message.userId = reader.int32();
                    break;
                case /* string date */ 2:
                    message.date = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetFoodLogRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 user_id = 1; */
        if (message.userId !== 0)
            writer.tag(1, WireType.Varint).int32(message.userId);
        /* string date = 2; */
        if (message.date !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.date);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.GetFoodLogRequest
 */
export const GetFoodLogRequest = new GetFoodLogRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetFoodLogResponse$Type extends MessageType<GetFoodLogResponse> {
    constructor() {
        super("proto.GetFoodLogResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "record", kind: "message", T: () => FoodLog }
        ]);
    }
    create(value?: PartialMessage<GetFoodLogResponse>): GetFoodLogResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<GetFoodLogResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetFoodLogResponse): GetFoodLogResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* proto.FoodLog record */ 3:
                    message.record = FoodLog.internalBinaryRead(reader, reader.uint32(), options, message.record);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetFoodLogResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* proto.FoodLog record = 3; */
        if (message.record)
            FoodLog.internalBinaryWrite(message.record, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.GetFoodLogResponse
 */
export const GetFoodLogResponse = new GetFoodLogResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetFoodLogsRequest$Type extends MessageType<GetFoodLogsRequest> {
    constructor() {
        super("proto.GetFoodLogsRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "start_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "end_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetFoodLogsRequest>): GetFoodLogsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = 0;
        message.startDate = "";
        message.endDate = "";
        if (value !== undefined)
            reflectionMergePartial<GetFoodLogsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetFoodLogsRequest): GetFoodLogsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 user_id */ 1:
                    message.userId = reader.int32();
                    break;
                case /* string start_date */ 2:
                    message.startDate = reader.string();
                    break;
                case /* string end_date */ 3:
                    message.endDate = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetFoodLogsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 user_id = 1; */
        if (message.userId !== 0)
            writer.tag(1, WireType.Varint).int32(message.userId);
        /* string start_date = 2; */
        if (message.startDate !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.startDate);
        /* string end_date = 3; */
        if (message.endDate !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.endDate);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.GetFoodLogsRequest
 */
export const GetFoodLogsRequest = new GetFoodLogsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetFoodLogsResponse$Type extends MessageType<GetFoodLogsResponse> {
    constructor() {
        super("proto.GetFoodLogsResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "records", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => FoodLog }
        ]);
    }
    create(value?: PartialMessage<GetFoodLogsResponse>): GetFoodLogsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        message.records = [];
        if (value !== undefined)
            reflectionMergePartial<GetFoodLogsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetFoodLogsResponse): GetFoodLogsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* repeated proto.FoodLog records */ 3:
                    message.records.push(FoodLog.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetFoodLogsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* repeated proto.FoodLog records = 3; */
        for (let i = 0; i < message.records.length; i++)
            FoodLog.internalBinaryWrite(message.records[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.GetFoodLogsResponse
 */
export const GetFoodLogsResponse = new GetFoodLogsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetFoodLogDatesRequest$Type extends MessageType<GetFoodLogDatesRequest> {
    constructor() {
        super("proto.GetFoodLogDatesRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "year", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "month", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetFoodLogDatesRequest>): GetFoodLogDatesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = 0;
        message.year = 0;
        message.month = 0;
        if (value !== undefined)
            reflectionMergePartial<GetFoodLogDatesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetFoodLogDatesRequest): GetFoodLogDatesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 user_id */ 1:
                    message.userId = reader.int32();
                    break;
                case /* int32 year */ 2:
                    message.year = reader.int32();
                    break;
                case /* int32 month */ 3:
                    message.month = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetFoodLogDatesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 user_id = 1; */
        if (message.userId !== 0)
            writer.tag(1, WireType.Varint).int32(message.userId);
        /* int32 year = 2; */
        if (message.year !== 0)
            writer.tag(2, WireType.Varint).int32(message.year);
        /* int32 month = 3; */
        if (message.month !== 0)
            writer.tag(3, WireType.Varint).int32(message.month);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.GetFoodLogDatesRequest
 */
export const GetFoodLogDatesRequest = new GetFoodLogDatesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetFoodLogDatesResponse$Type extends MessageType<GetFoodLogDatesResponse> {
    constructor() {
        super("proto.GetFoodLogDatesResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "recorded_days", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetFoodLogDatesResponse>): GetFoodLogDatesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        message.recordedDays = [];
        if (value !== undefined)
            reflectionMergePartial<GetFoodLogDatesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetFoodLogDatesResponse): GetFoodLogDatesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* repeated int32 recorded_days */ 3:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.recordedDays.push(reader.int32());
                    else
                        message.recordedDays.push(reader.int32());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetFoodLogDatesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* repeated int32 recorded_days = 3; */
        if (message.recordedDays.length) {
            writer.tag(3, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.recordedDays.length; i++)
                writer.int32(message.recordedDays[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.GetFoodLogDatesResponse
 */
export const GetFoodLogDatesResponse = new GetFoodLogDatesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FoodLog$Type extends MessageType<FoodLog> {
    constructor() {
        super("proto.FoodLog", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "diary", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "photos", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "is_public", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<FoodLog>): FoodLog {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.userId = 0;
        message.date = "";
        message.diary = "";
        message.photos = [];
        message.isPublic = false;
        message.createdAt = "";
        message.updatedAt = "";
        if (value !== undefined)
            reflectionMergePartial<FoodLog>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FoodLog): FoodLog {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* int32 user_id */ 2:
                    message.userId = reader.int32();
                    break;
                case /* string date */ 3:
                    message.date = reader.string();
                    break;
                case /* string diary */ 4:
                    message.diary = reader.string();
                    break;
                case /* repeated string photos */ 5:
                    message.photos.push(reader.string());
                    break;
                case /* bool is_public */ 6:
                    message.isPublic = reader.bool();
                    break;
                case /* string created_at */ 7:
                    message.createdAt = reader.string();
                    break;
                case /* string updated_at */ 8:
                    message.updatedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FoodLog, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* int32 user_id = 2; */
        if (message.userId !== 0)
            writer.tag(2, WireType.Varint).int32(message.userId);
        /* string date = 3; */
        if (message.date !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.date);
        /* string diary = 4; */
        if (message.diary !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.diary);
        /* repeated string photos = 5; */
        for (let i = 0; i < message.photos.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.photos[i]);
        /* bool is_public = 6; */
        if (message.isPublic !== false)
            writer.tag(6, WireType.Varint).bool(message.isPublic);
        /* string created_at = 7; */
        if (message.createdAt !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.createdAt);
        /* string updated_at = 8; */
        if (message.updatedAt !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.updatedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.FoodLog
 */
export const FoodLog = new FoodLog$Type();
