// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "notification.proto" (package "notification", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Notification message
 *
 * @generated from protobuf message notification.Notification
 */
export interface Notification {
    /**
     * @generated from protobuf field: uint32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: uint32 user_id = 2
     */
    userId: number;
    /**
     * @generated from protobuf field: notification.NotificationType type = 3
     */
    type: NotificationType;
    /**
     * @generated from protobuf field: string title = 4
     */
    title: string;
    /**
     * @generated from protobuf field: string message = 5
     */
    message: string;
    /**
     * @generated from protobuf field: string action_url = 6
     */
    actionUrl: string;
    /**
     * @generated from protobuf field: bool is_read = 7
     */
    isRead: boolean;
    /**
     * @generated from protobuf field: uint32 related_user_id = 8
     */
    relatedUserId: number;
    /**
     * @generated from protobuf field: string related_user_name = 9
     */
    relatedUserName: string;
    /**
     * @generated from protobuf field: string related_user_picture = 10
     */
    relatedUserPicture: string;
    /**
     * @generated from protobuf field: uint32 related_post_id = 11
     */
    relatedPostId: number;
    /**
     * @generated from protobuf field: string related_post_content = 12
     */
    relatedPostContent: string;
    /**
     * @generated from protobuf field: string created_at = 13
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string updated_at = 14
     */
    updatedAt: string;
}
/**
 * Notification Settings message
 *
 * @generated from protobuf message notification.NotificationSettings
 */
export interface NotificationSettings {
    /**
     * @generated from protobuf field: uint32 user_id = 1
     */
    userId: number;
    /**
     * @generated from protobuf field: bool like_notifications = 2
     */
    likeNotifications: boolean;
    /**
     * @generated from protobuf field: bool comment_notifications = 3
     */
    commentNotifications: boolean;
    /**
     * @generated from protobuf field: bool follow_notifications = 4
     */
    followNotifications: boolean;
    /**
     * @generated from protobuf field: bool retweet_notifications = 5
     */
    retweetNotifications: boolean;
    /**
     * @generated from protobuf field: bool message_notifications = 6
     */
    messageNotifications: boolean;
    /**
     * @generated from protobuf field: bool system_notifications = 7
     */
    systemNotifications: boolean;
    /**
     * @generated from protobuf field: bool email_notifications = 8
     */
    emailNotifications: boolean;
    /**
     * @generated from protobuf field: bool push_notifications = 9
     */
    pushNotifications: boolean;
    /**
     * @generated from protobuf field: string updated_at = 10
     */
    updatedAt: string;
}
/**
 * Request messages
 *
 * @generated from protobuf message notification.NotificationListRequest
 */
export interface NotificationListRequest {
    /**
     * @generated from protobuf field: uint32 page = 1
     */
    page: number;
    /**
     * @generated from protobuf field: uint32 limit = 2
     */
    limit: number;
    /**
     * @generated from protobuf field: bool unread_only = 3
     */
    unreadOnly: boolean;
    /**
     * @generated from protobuf field: repeated notification.NotificationType types = 4
     */
    types: NotificationType[];
}
/**
 * @generated from protobuf message notification.MarkAsReadRequest
 */
export interface MarkAsReadRequest {
    /**
     * @generated from protobuf field: uint32 notification_id = 1
     */
    notificationId: number;
}
/**
 * Empty message - marks all notifications as read for the authenticated user
 *
 * @generated from protobuf message notification.MarkAllAsReadRequest
 */
export interface MarkAllAsReadRequest {
}
/**
 * @generated from protobuf message notification.UpdateNotificationSettingsRequest
 */
export interface UpdateNotificationSettingsRequest {
    /**
     * @generated from protobuf field: bool like_notifications = 1
     */
    likeNotifications: boolean;
    /**
     * @generated from protobuf field: bool comment_notifications = 2
     */
    commentNotifications: boolean;
    /**
     * @generated from protobuf field: bool follow_notifications = 3
     */
    followNotifications: boolean;
    /**
     * @generated from protobuf field: bool retweet_notifications = 4
     */
    retweetNotifications: boolean;
    /**
     * @generated from protobuf field: bool message_notifications = 5
     */
    messageNotifications: boolean;
    /**
     * @generated from protobuf field: bool system_notifications = 6
     */
    systemNotifications: boolean;
    /**
     * @generated from protobuf field: bool email_notifications = 7
     */
    emailNotifications: boolean;
    /**
     * @generated from protobuf field: bool push_notifications = 8
     */
    pushNotifications: boolean;
}
/**
 * Response messages
 *
 * @generated from protobuf message notification.NotificationsResponse
 */
export interface NotificationsResponse {
    /**
     * @generated from protobuf field: repeated notification.Notification notifications = 1
     */
    notifications: Notification[];
    /**
     * @generated from protobuf field: uint32 total_count = 2
     */
    totalCount: number;
    /**
     * @generated from protobuf field: uint32 unread_count = 3
     */
    unreadCount: number;
    /**
     * @generated from protobuf field: bool has_more = 4
     */
    hasMore: boolean;
}
/**
 * @generated from protobuf message notification.NotificationSettingsResponse
 */
export interface NotificationSettingsResponse {
    /**
     * @generated from protobuf field: notification.NotificationSettings settings = 1
     */
    settings?: NotificationSettings;
}
/**
 * @generated from protobuf message notification.NotificationUnreadCountResponse
 */
export interface NotificationUnreadCountResponse {
    /**
     * @generated from protobuf field: uint32 unread_count = 1
     */
    unreadCount: number;
}
/**
 * @generated from protobuf message notification.NotificationResponse
 */
export interface NotificationResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * Notification Type enum
 *
 * @generated from protobuf enum notification.NotificationType
 */
export enum NotificationType {
    /**
     * @generated from protobuf enum value: UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: LIKE = 1;
     */
    LIKE = 1,
    /**
     * @generated from protobuf enum value: COMMENT = 2;
     */
    COMMENT = 2,
    /**
     * @generated from protobuf enum value: FOLLOW = 3;
     */
    FOLLOW = 3,
    /**
     * @generated from protobuf enum value: RETWEET = 4;
     */
    RETWEET = 4,
    /**
     * @generated from protobuf enum value: MESSAGE = 5;
     */
    MESSAGE = 5,
    /**
     * @generated from protobuf enum value: SYSTEM = 6;
     */
    SYSTEM = 6
}
// @generated message type with reflection information, may provide speed optimized methods
class Notification$Type extends MessageType<Notification> {
    constructor() {
        super("notification.Notification", [
            { no: 1, name: "id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "type", kind: "enum", T: () => ["notification.NotificationType", NotificationType] },
            { no: 4, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "action_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "is_read", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "related_user_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 9, name: "related_user_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "related_user_picture", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "related_post_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 12, name: "related_post_content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Notification>): Notification {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.userId = 0;
        message.type = 0;
        message.title = "";
        message.message = "";
        message.actionUrl = "";
        message.isRead = false;
        message.relatedUserId = 0;
        message.relatedUserName = "";
        message.relatedUserPicture = "";
        message.relatedPostId = 0;
        message.relatedPostContent = "";
        message.createdAt = "";
        message.updatedAt = "";
        if (value !== undefined)
            reflectionMergePartial<Notification>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Notification): Notification {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 id */ 1:
                    message.id = reader.uint32();
                    break;
                case /* uint32 user_id */ 2:
                    message.userId = reader.uint32();
                    break;
                case /* notification.NotificationType type */ 3:
                    message.type = reader.int32();
                    break;
                case /* string title */ 4:
                    message.title = reader.string();
                    break;
                case /* string message */ 5:
                    message.message = reader.string();
                    break;
                case /* string action_url */ 6:
                    message.actionUrl = reader.string();
                    break;
                case /* bool is_read */ 7:
                    message.isRead = reader.bool();
                    break;
                case /* uint32 related_user_id */ 8:
                    message.relatedUserId = reader.uint32();
                    break;
                case /* string related_user_name */ 9:
                    message.relatedUserName = reader.string();
                    break;
                case /* string related_user_picture */ 10:
                    message.relatedUserPicture = reader.string();
                    break;
                case /* uint32 related_post_id */ 11:
                    message.relatedPostId = reader.uint32();
                    break;
                case /* string related_post_content */ 12:
                    message.relatedPostContent = reader.string();
                    break;
                case /* string created_at */ 13:
                    message.createdAt = reader.string();
                    break;
                case /* string updated_at */ 14:
                    message.updatedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Notification, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).uint32(message.id);
        /* uint32 user_id = 2; */
        if (message.userId !== 0)
            writer.tag(2, WireType.Varint).uint32(message.userId);
        /* notification.NotificationType type = 3; */
        if (message.type !== 0)
            writer.tag(3, WireType.Varint).int32(message.type);
        /* string title = 4; */
        if (message.title !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.title);
        /* string message = 5; */
        if (message.message !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.message);
        /* string action_url = 6; */
        if (message.actionUrl !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.actionUrl);
        /* bool is_read = 7; */
        if (message.isRead !== false)
            writer.tag(7, WireType.Varint).bool(message.isRead);
        /* uint32 related_user_id = 8; */
        if (message.relatedUserId !== 0)
            writer.tag(8, WireType.Varint).uint32(message.relatedUserId);
        /* string related_user_name = 9; */
        if (message.relatedUserName !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.relatedUserName);
        /* string related_user_picture = 10; */
        if (message.relatedUserPicture !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.relatedUserPicture);
        /* uint32 related_post_id = 11; */
        if (message.relatedPostId !== 0)
            writer.tag(11, WireType.Varint).uint32(message.relatedPostId);
        /* string related_post_content = 12; */
        if (message.relatedPostContent !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.relatedPostContent);
        /* string created_at = 13; */
        if (message.createdAt !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.createdAt);
        /* string updated_at = 14; */
        if (message.updatedAt !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.updatedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message notification.Notification
 */
export const Notification = new Notification$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotificationSettings$Type extends MessageType<NotificationSettings> {
    constructor() {
        super("notification.NotificationSettings", [
            { no: 1, name: "user_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "like_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "comment_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "follow_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "retweet_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "message_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "system_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "email_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 9, name: "push_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<NotificationSettings>): NotificationSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = 0;
        message.likeNotifications = false;
        message.commentNotifications = false;
        message.followNotifications = false;
        message.retweetNotifications = false;
        message.messageNotifications = false;
        message.systemNotifications = false;
        message.emailNotifications = false;
        message.pushNotifications = false;
        message.updatedAt = "";
        if (value !== undefined)
            reflectionMergePartial<NotificationSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotificationSettings): NotificationSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 user_id */ 1:
                    message.userId = reader.uint32();
                    break;
                case /* bool like_notifications */ 2:
                    message.likeNotifications = reader.bool();
                    break;
                case /* bool comment_notifications */ 3:
                    message.commentNotifications = reader.bool();
                    break;
                case /* bool follow_notifications */ 4:
                    message.followNotifications = reader.bool();
                    break;
                case /* bool retweet_notifications */ 5:
                    message.retweetNotifications = reader.bool();
                    break;
                case /* bool message_notifications */ 6:
                    message.messageNotifications = reader.bool();
                    break;
                case /* bool system_notifications */ 7:
                    message.systemNotifications = reader.bool();
                    break;
                case /* bool email_notifications */ 8:
                    message.emailNotifications = reader.bool();
                    break;
                case /* bool push_notifications */ 9:
                    message.pushNotifications = reader.bool();
                    break;
                case /* string updated_at */ 10:
                    message.updatedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotificationSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 user_id = 1; */
        if (message.userId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.userId);
        /* bool like_notifications = 2; */
        if (message.likeNotifications !== false)
            writer.tag(2, WireType.Varint).bool(message.likeNotifications);
        /* bool comment_notifications = 3; */
        if (message.commentNotifications !== false)
            writer.tag(3, WireType.Varint).bool(message.commentNotifications);
        /* bool follow_notifications = 4; */
        if (message.followNotifications !== false)
            writer.tag(4, WireType.Varint).bool(message.followNotifications);
        /* bool retweet_notifications = 5; */
        if (message.retweetNotifications !== false)
            writer.tag(5, WireType.Varint).bool(message.retweetNotifications);
        /* bool message_notifications = 6; */
        if (message.messageNotifications !== false)
            writer.tag(6, WireType.Varint).bool(message.messageNotifications);
        /* bool system_notifications = 7; */
        if (message.systemNotifications !== false)
            writer.tag(7, WireType.Varint).bool(message.systemNotifications);
        /* bool email_notifications = 8; */
        if (message.emailNotifications !== false)
            writer.tag(8, WireType.Varint).bool(message.emailNotifications);
        /* bool push_notifications = 9; */
        if (message.pushNotifications !== false)
            writer.tag(9, WireType.Varint).bool(message.pushNotifications);
        /* string updated_at = 10; */
        if (message.updatedAt !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.updatedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message notification.NotificationSettings
 */
export const NotificationSettings = new NotificationSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotificationListRequest$Type extends MessageType<NotificationListRequest> {
    constructor() {
        super("notification.NotificationListRequest", [
            { no: 1, name: "page", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "limit", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "unread_only", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "types", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["notification.NotificationType", NotificationType] }
        ]);
    }
    create(value?: PartialMessage<NotificationListRequest>): NotificationListRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.page = 0;
        message.limit = 0;
        message.unreadOnly = false;
        message.types = [];
        if (value !== undefined)
            reflectionMergePartial<NotificationListRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotificationListRequest): NotificationListRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 page */ 1:
                    message.page = reader.uint32();
                    break;
                case /* uint32 limit */ 2:
                    message.limit = reader.uint32();
                    break;
                case /* bool unread_only */ 3:
                    message.unreadOnly = reader.bool();
                    break;
                case /* repeated notification.NotificationType types */ 4:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.types.push(reader.int32());
                    else
                        message.types.push(reader.int32());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotificationListRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 page = 1; */
        if (message.page !== 0)
            writer.tag(1, WireType.Varint).uint32(message.page);
        /* uint32 limit = 2; */
        if (message.limit !== 0)
            writer.tag(2, WireType.Varint).uint32(message.limit);
        /* bool unread_only = 3; */
        if (message.unreadOnly !== false)
            writer.tag(3, WireType.Varint).bool(message.unreadOnly);
        /* repeated notification.NotificationType types = 4; */
        if (message.types.length) {
            writer.tag(4, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.types.length; i++)
                writer.int32(message.types[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message notification.NotificationListRequest
 */
export const NotificationListRequest = new NotificationListRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MarkAsReadRequest$Type extends MessageType<MarkAsReadRequest> {
    constructor() {
        super("notification.MarkAsReadRequest", [
            { no: 1, name: "notification_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<MarkAsReadRequest>): MarkAsReadRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.notificationId = 0;
        if (value !== undefined)
            reflectionMergePartial<MarkAsReadRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MarkAsReadRequest): MarkAsReadRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 notification_id */ 1:
                    message.notificationId = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MarkAsReadRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 notification_id = 1; */
        if (message.notificationId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.notificationId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message notification.MarkAsReadRequest
 */
export const MarkAsReadRequest = new MarkAsReadRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MarkAllAsReadRequest$Type extends MessageType<MarkAllAsReadRequest> {
    constructor() {
        super("notification.MarkAllAsReadRequest", []);
    }
    create(value?: PartialMessage<MarkAllAsReadRequest>): MarkAllAsReadRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<MarkAllAsReadRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MarkAllAsReadRequest): MarkAllAsReadRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MarkAllAsReadRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message notification.MarkAllAsReadRequest
 */
export const MarkAllAsReadRequest = new MarkAllAsReadRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateNotificationSettingsRequest$Type extends MessageType<UpdateNotificationSettingsRequest> {
    constructor() {
        super("notification.UpdateNotificationSettingsRequest", [
            { no: 1, name: "like_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "comment_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "follow_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "retweet_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "message_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "system_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "email_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "push_notifications", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateNotificationSettingsRequest>): UpdateNotificationSettingsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.likeNotifications = false;
        message.commentNotifications = false;
        message.followNotifications = false;
        message.retweetNotifications = false;
        message.messageNotifications = false;
        message.systemNotifications = false;
        message.emailNotifications = false;
        message.pushNotifications = false;
        if (value !== undefined)
            reflectionMergePartial<UpdateNotificationSettingsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateNotificationSettingsRequest): UpdateNotificationSettingsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool like_notifications */ 1:
                    message.likeNotifications = reader.bool();
                    break;
                case /* bool comment_notifications */ 2:
                    message.commentNotifications = reader.bool();
                    break;
                case /* bool follow_notifications */ 3:
                    message.followNotifications = reader.bool();
                    break;
                case /* bool retweet_notifications */ 4:
                    message.retweetNotifications = reader.bool();
                    break;
                case /* bool message_notifications */ 5:
                    message.messageNotifications = reader.bool();
                    break;
                case /* bool system_notifications */ 6:
                    message.systemNotifications = reader.bool();
                    break;
                case /* bool email_notifications */ 7:
                    message.emailNotifications = reader.bool();
                    break;
                case /* bool push_notifications */ 8:
                    message.pushNotifications = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateNotificationSettingsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool like_notifications = 1; */
        if (message.likeNotifications !== false)
            writer.tag(1, WireType.Varint).bool(message.likeNotifications);
        /* bool comment_notifications = 2; */
        if (message.commentNotifications !== false)
            writer.tag(2, WireType.Varint).bool(message.commentNotifications);
        /* bool follow_notifications = 3; */
        if (message.followNotifications !== false)
            writer.tag(3, WireType.Varint).bool(message.followNotifications);
        /* bool retweet_notifications = 4; */
        if (message.retweetNotifications !== false)
            writer.tag(4, WireType.Varint).bool(message.retweetNotifications);
        /* bool message_notifications = 5; */
        if (message.messageNotifications !== false)
            writer.tag(5, WireType.Varint).bool(message.messageNotifications);
        /* bool system_notifications = 6; */
        if (message.systemNotifications !== false)
            writer.tag(6, WireType.Varint).bool(message.systemNotifications);
        /* bool email_notifications = 7; */
        if (message.emailNotifications !== false)
            writer.tag(7, WireType.Varint).bool(message.emailNotifications);
        /* bool push_notifications = 8; */
        if (message.pushNotifications !== false)
            writer.tag(8, WireType.Varint).bool(message.pushNotifications);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message notification.UpdateNotificationSettingsRequest
 */
export const UpdateNotificationSettingsRequest = new UpdateNotificationSettingsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotificationsResponse$Type extends MessageType<NotificationsResponse> {
    constructor() {
        super("notification.NotificationsResponse", [
            { no: 1, name: "notifications", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Notification },
            { no: 2, name: "total_count", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "unread_count", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "has_more", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<NotificationsResponse>): NotificationsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.notifications = [];
        message.totalCount = 0;
        message.unreadCount = 0;
        message.hasMore = false;
        if (value !== undefined)
            reflectionMergePartial<NotificationsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotificationsResponse): NotificationsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated notification.Notification notifications */ 1:
                    message.notifications.push(Notification.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* uint32 total_count */ 2:
                    message.totalCount = reader.uint32();
                    break;
                case /* uint32 unread_count */ 3:
                    message.unreadCount = reader.uint32();
                    break;
                case /* bool has_more */ 4:
                    message.hasMore = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotificationsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated notification.Notification notifications = 1; */
        for (let i = 0; i < message.notifications.length; i++)
            Notification.internalBinaryWrite(message.notifications[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* uint32 total_count = 2; */
        if (message.totalCount !== 0)
            writer.tag(2, WireType.Varint).uint32(message.totalCount);
        /* uint32 unread_count = 3; */
        if (message.unreadCount !== 0)
            writer.tag(3, WireType.Varint).uint32(message.unreadCount);
        /* bool has_more = 4; */
        if (message.hasMore !== false)
            writer.tag(4, WireType.Varint).bool(message.hasMore);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message notification.NotificationsResponse
 */
export const NotificationsResponse = new NotificationsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotificationSettingsResponse$Type extends MessageType<NotificationSettingsResponse> {
    constructor() {
        super("notification.NotificationSettingsResponse", [
            { no: 1, name: "settings", kind: "message", T: () => NotificationSettings }
        ]);
    }
    create(value?: PartialMessage<NotificationSettingsResponse>): NotificationSettingsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<NotificationSettingsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotificationSettingsResponse): NotificationSettingsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* notification.NotificationSettings settings */ 1:
                    message.settings = NotificationSettings.internalBinaryRead(reader, reader.uint32(), options, message.settings);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotificationSettingsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* notification.NotificationSettings settings = 1; */
        if (message.settings)
            NotificationSettings.internalBinaryWrite(message.settings, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message notification.NotificationSettingsResponse
 */
export const NotificationSettingsResponse = new NotificationSettingsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotificationUnreadCountResponse$Type extends MessageType<NotificationUnreadCountResponse> {
    constructor() {
        super("notification.NotificationUnreadCountResponse", [
            { no: 1, name: "unread_count", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<NotificationUnreadCountResponse>): NotificationUnreadCountResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.unreadCount = 0;
        if (value !== undefined)
            reflectionMergePartial<NotificationUnreadCountResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotificationUnreadCountResponse): NotificationUnreadCountResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 unread_count */ 1:
                    message.unreadCount = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotificationUnreadCountResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 unread_count = 1; */
        if (message.unreadCount !== 0)
            writer.tag(1, WireType.Varint).uint32(message.unreadCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message notification.NotificationUnreadCountResponse
 */
export const NotificationUnreadCountResponse = new NotificationUnreadCountResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotificationResponse$Type extends MessageType<NotificationResponse> {
    constructor() {
        super("notification.NotificationResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<NotificationResponse>): NotificationResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<NotificationResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotificationResponse): NotificationResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotificationResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message notification.NotificationResponse
 */
export const NotificationResponse = new NotificationResponse$Type();
