// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "user_profile.proto" (package "proto", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message proto.UserProfile
 */
export interface UserProfile {
    /**
     * @generated from protobuf field: uint32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: uint32 user_id = 2
     */
    userId: number;
    /**
     * @generated from protobuf field: string display_name = 3
     */
    displayName: string;
    /**
     * @generated from protobuf field: optional int32 selected_preset_id = 4
     */
    selectedPresetId?: number;
    /**
     * @generated from protobuf field: string icon_type = 5
     */
    iconType: string;
    /**
     * @generated from protobuf field: optional string uploaded_icon = 6
     */
    uploadedIcon?: string;
    /**
     * @generated from protobuf field: optional string uploaded_icon_public_id = 23
     */
    uploadedIconPublicId?: string;
    /**
     * @generated from protobuf field: string gender = 7
     */
    gender: string;
    /**
     * @generated from protobuf field: optional int32 age = 8
     */
    age?: number;
    /**
     * @generated from protobuf field: optional double height = 9
     */
    height?: number;
    /**
     * @generated from protobuf field: string activity_level = 10
     */
    activityLevel: string;
    /**
     * @generated from protobuf field: optional double current_weight = 11
     */
    currentWeight?: number;
    /**
     * @generated from protobuf field: optional double target_weight = 12
     */
    targetWeight?: number;
    /**
     * @generated from protobuf field: bool show_preset = 13
     */
    showPreset: boolean;
    /**
     * @generated from protobuf field: string pr_text = 14
     */
    prText: string;
    /**
     * @generated from protobuf field: bool is_gender_private = 15
     */
    isGenderPrivate: boolean;
    /**
     * @generated from protobuf field: bool is_age_private = 16
     */
    isAgePrivate: boolean;
    /**
     * @generated from protobuf field: bool is_height_private = 17
     */
    isHeightPrivate: boolean;
    /**
     * @generated from protobuf field: bool is_activity_private = 18
     */
    isActivityPrivate: boolean;
    /**
     * @generated from protobuf field: bool is_current_weight_private = 19
     */
    isCurrentWeightPrivate: boolean;
    /**
     * @generated from protobuf field: bool is_target_weight_private = 20
     */
    isTargetWeightPrivate: boolean;
    /**
     * @generated from protobuf field: bool enable_sensitive_filter = 24
     */
    enableSensitiveFilter: boolean;
    /**
     * @generated from protobuf field: bool enable_global_filter = 25
     */
    enableGlobalFilter: boolean;
    /**
     * @generated from protobuf field: string created_at = 21
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string updated_at = 22
     */
    updatedAt: string;
}
/**
 * @generated from protobuf message proto.CreateUserProfileRequest
 */
export interface CreateUserProfileRequest {
    /**
     * @generated from protobuf field: uint32 user_id = 1
     */
    userId: number;
    /**
     * @generated from protobuf field: string display_name = 2
     */
    displayName: string;
    /**
     * @generated from protobuf field: optional int32 selected_preset_id = 3
     */
    selectedPresetId?: number;
    /**
     * @generated from protobuf field: string icon_type = 4
     */
    iconType: string;
    /**
     * @generated from protobuf field: optional string uploaded_icon = 5
     */
    uploadedIcon?: string;
    /**
     * @generated from protobuf field: optional string uploaded_icon_public_id = 20
     */
    uploadedIconPublicId?: string;
    /**
     * @generated from protobuf field: string gender = 6
     */
    gender: string;
    /**
     * @generated from protobuf field: optional int32 age = 7
     */
    age?: number;
    /**
     * @generated from protobuf field: optional double height = 8
     */
    height?: number;
    /**
     * @generated from protobuf field: string activity_level = 9
     */
    activityLevel: string;
    /**
     * @generated from protobuf field: optional double current_weight = 10
     */
    currentWeight?: number;
    /**
     * @generated from protobuf field: optional double target_weight = 11
     */
    targetWeight?: number;
    /**
     * @generated from protobuf field: bool show_preset = 12
     */
    showPreset: boolean;
    /**
     * @generated from protobuf field: string pr_text = 13
     */
    prText: string;
    /**
     * @generated from protobuf field: bool is_gender_private = 14
     */
    isGenderPrivate: boolean;
    /**
     * @generated from protobuf field: bool is_age_private = 15
     */
    isAgePrivate: boolean;
    /**
     * @generated from protobuf field: bool is_height_private = 16
     */
    isHeightPrivate: boolean;
    /**
     * @generated from protobuf field: bool is_activity_private = 17
     */
    isActivityPrivate: boolean;
    /**
     * @generated from protobuf field: bool is_current_weight_private = 18
     */
    isCurrentWeightPrivate: boolean;
    /**
     * @generated from protobuf field: bool is_target_weight_private = 19
     */
    isTargetWeightPrivate: boolean;
    /**
     * @generated from protobuf field: bool enable_sensitive_filter = 21
     */
    enableSensitiveFilter: boolean;
    /**
     * @generated from protobuf field: bool enable_global_filter = 22
     */
    enableGlobalFilter: boolean;
}
/**
 * @generated from protobuf message proto.CreateUserProfileResponse
 */
export interface CreateUserProfileResponse {
    /**
     * @generated from protobuf field: proto.UserProfile profile = 1
     */
    profile?: UserProfile;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message proto.GetUserProfileRequest
 */
export interface GetUserProfileRequest {
    /**
     * @generated from protobuf field: uint32 user_id = 1
     */
    userId: number;
}
/**
 * @generated from protobuf message proto.GetUserProfileResponse
 */
export interface GetUserProfileResponse {
    /**
     * @generated from protobuf field: proto.UserProfile profile = 1
     */
    profile?: UserProfile;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message proto.UpdateUserProfileRequest
 */
export interface UpdateUserProfileRequest {
    /**
     * @generated from protobuf field: uint32 user_id = 1
     */
    userId: number;
    /**
     * @generated from protobuf field: string display_name = 2
     */
    displayName: string;
    /**
     * @generated from protobuf field: optional int32 selected_preset_id = 3
     */
    selectedPresetId?: number;
    /**
     * @generated from protobuf field: string icon_type = 4
     */
    iconType: string;
    /**
     * @generated from protobuf field: optional string uploaded_icon = 5
     */
    uploadedIcon?: string;
    /**
     * @generated from protobuf field: string gender = 6
     */
    gender: string;
    /**
     * @generated from protobuf field: optional int32 age = 7
     */
    age?: number;
    /**
     * @generated from protobuf field: optional double height = 8
     */
    height?: number;
    /**
     * @generated from protobuf field: string activity_level = 9
     */
    activityLevel: string;
    /**
     * @generated from protobuf field: optional double current_weight = 10
     */
    currentWeight?: number;
    /**
     * @generated from protobuf field: optional double target_weight = 11
     */
    targetWeight?: number;
    /**
     * @generated from protobuf field: bool show_preset = 12
     */
    showPreset: boolean;
    /**
     * @generated from protobuf field: string pr_text = 13
     */
    prText: string;
    /**
     * @generated from protobuf field: bool is_gender_private = 14
     */
    isGenderPrivate: boolean;
    /**
     * @generated from protobuf field: bool is_age_private = 15
     */
    isAgePrivate: boolean;
    /**
     * @generated from protobuf field: bool is_height_private = 16
     */
    isHeightPrivate: boolean;
    /**
     * @generated from protobuf field: bool is_activity_private = 17
     */
    isActivityPrivate: boolean;
    /**
     * @generated from protobuf field: bool is_current_weight_private = 18
     */
    isCurrentWeightPrivate: boolean;
    /**
     * @generated from protobuf field: bool is_target_weight_private = 19
     */
    isTargetWeightPrivate: boolean;
    /**
     * @generated from protobuf field: bool enable_sensitive_filter = 20
     */
    enableSensitiveFilter: boolean;
}
/**
 * @generated from protobuf message proto.UpdateUserProfileResponse
 */
export interface UpdateUserProfileResponse {
    /**
     * @generated from protobuf field: proto.UserProfile profile = 1
     */
    profile?: UserProfile;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message proto.UploadUserIconRequest
 */
export interface UploadUserIconRequest {
    /**
     * @generated from protobuf field: bytes image_data = 1
     */
    imageData: Uint8Array;
    /**
     * @generated from protobuf field: string file_name = 2
     */
    fileName: string;
}
/**
 * @generated from protobuf message proto.UploadUserIconResponse
 */
export interface UploadUserIconResponse {
    /**
     * @generated from protobuf field: string url = 1
     */
    url: string;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: string public_id = 3
     */
    publicId: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class UserProfile$Type extends MessageType<UserProfile> {
    constructor() {
        super("proto.UserProfile", [
            { no: 1, name: "id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "display_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "selected_preset_id", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "icon_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "uploaded_icon", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 23, name: "uploaded_icon_public_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "gender", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "age", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "height", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 10, name: "activity_level", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "current_weight", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 12, name: "target_weight", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 13, name: "show_preset", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 14, name: "pr_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "is_gender_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 16, name: "is_age_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 17, name: "is_height_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 18, name: "is_activity_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 19, name: "is_current_weight_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 20, name: "is_target_weight_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 24, name: "enable_sensitive_filter", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 25, name: "enable_global_filter", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 21, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 22, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UserProfile>): UserProfile {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.userId = 0;
        message.displayName = "";
        message.iconType = "";
        message.gender = "";
        message.activityLevel = "";
        message.showPreset = false;
        message.prText = "";
        message.isGenderPrivate = false;
        message.isAgePrivate = false;
        message.isHeightPrivate = false;
        message.isActivityPrivate = false;
        message.isCurrentWeightPrivate = false;
        message.isTargetWeightPrivate = false;
        message.enableSensitiveFilter = false;
        message.enableGlobalFilter = false;
        message.createdAt = "";
        message.updatedAt = "";
        if (value !== undefined)
            reflectionMergePartial<UserProfile>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserProfile): UserProfile {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 id */ 1:
                    message.id = reader.uint32();
                    break;
                case /* uint32 user_id */ 2:
                    message.userId = reader.uint32();
                    break;
                case /* string display_name */ 3:
                    message.displayName = reader.string();
                    break;
                case /* optional int32 selected_preset_id */ 4:
                    message.selectedPresetId = reader.int32();
                    break;
                case /* string icon_type */ 5:
                    message.iconType = reader.string();
                    break;
                case /* optional string uploaded_icon */ 6:
                    message.uploadedIcon = reader.string();
                    break;
                case /* optional string uploaded_icon_public_id */ 23:
                    message.uploadedIconPublicId = reader.string();
                    break;
                case /* string gender */ 7:
                    message.gender = reader.string();
                    break;
                case /* optional int32 age */ 8:
                    message.age = reader.int32();
                    break;
                case /* optional double height */ 9:
                    message.height = reader.double();
                    break;
                case /* string activity_level */ 10:
                    message.activityLevel = reader.string();
                    break;
                case /* optional double current_weight */ 11:
                    message.currentWeight = reader.double();
                    break;
                case /* optional double target_weight */ 12:
                    message.targetWeight = reader.double();
                    break;
                case /* bool show_preset */ 13:
                    message.showPreset = reader.bool();
                    break;
                case /* string pr_text */ 14:
                    message.prText = reader.string();
                    break;
                case /* bool is_gender_private */ 15:
                    message.isGenderPrivate = reader.bool();
                    break;
                case /* bool is_age_private */ 16:
                    message.isAgePrivate = reader.bool();
                    break;
                case /* bool is_height_private */ 17:
                    message.isHeightPrivate = reader.bool();
                    break;
                case /* bool is_activity_private */ 18:
                    message.isActivityPrivate = reader.bool();
                    break;
                case /* bool is_current_weight_private */ 19:
                    message.isCurrentWeightPrivate = reader.bool();
                    break;
                case /* bool is_target_weight_private */ 20:
                    message.isTargetWeightPrivate = reader.bool();
                    break;
                case /* bool enable_sensitive_filter */ 24:
                    message.enableSensitiveFilter = reader.bool();
                    break;
                case /* bool enable_global_filter */ 25:
                    message.enableGlobalFilter = reader.bool();
                    break;
                case /* string created_at */ 21:
                    message.createdAt = reader.string();
                    break;
                case /* string updated_at */ 22:
                    message.updatedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserProfile, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).uint32(message.id);
        /* uint32 user_id = 2; */
        if (message.userId !== 0)
            writer.tag(2, WireType.Varint).uint32(message.userId);
        /* string display_name = 3; */
        if (message.displayName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.displayName);
        /* optional int32 selected_preset_id = 4; */
        if (message.selectedPresetId !== undefined)
            writer.tag(4, WireType.Varint).int32(message.selectedPresetId);
        /* string icon_type = 5; */
        if (message.iconType !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.iconType);
        /* optional string uploaded_icon = 6; */
        if (message.uploadedIcon !== undefined)
            writer.tag(6, WireType.LengthDelimited).string(message.uploadedIcon);
        /* string gender = 7; */
        if (message.gender !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.gender);
        /* optional int32 age = 8; */
        if (message.age !== undefined)
            writer.tag(8, WireType.Varint).int32(message.age);
        /* optional double height = 9; */
        if (message.height !== undefined)
            writer.tag(9, WireType.Bit64).double(message.height);
        /* string activity_level = 10; */
        if (message.activityLevel !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.activityLevel);
        /* optional double current_weight = 11; */
        if (message.currentWeight !== undefined)
            writer.tag(11, WireType.Bit64).double(message.currentWeight);
        /* optional double target_weight = 12; */
        if (message.targetWeight !== undefined)
            writer.tag(12, WireType.Bit64).double(message.targetWeight);
        /* bool show_preset = 13; */
        if (message.showPreset !== false)
            writer.tag(13, WireType.Varint).bool(message.showPreset);
        /* string pr_text = 14; */
        if (message.prText !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.prText);
        /* bool is_gender_private = 15; */
        if (message.isGenderPrivate !== false)
            writer.tag(15, WireType.Varint).bool(message.isGenderPrivate);
        /* bool is_age_private = 16; */
        if (message.isAgePrivate !== false)
            writer.tag(16, WireType.Varint).bool(message.isAgePrivate);
        /* bool is_height_private = 17; */
        if (message.isHeightPrivate !== false)
            writer.tag(17, WireType.Varint).bool(message.isHeightPrivate);
        /* bool is_activity_private = 18; */
        if (message.isActivityPrivate !== false)
            writer.tag(18, WireType.Varint).bool(message.isActivityPrivate);
        /* bool is_current_weight_private = 19; */
        if (message.isCurrentWeightPrivate !== false)
            writer.tag(19, WireType.Varint).bool(message.isCurrentWeightPrivate);
        /* bool is_target_weight_private = 20; */
        if (message.isTargetWeightPrivate !== false)
            writer.tag(20, WireType.Varint).bool(message.isTargetWeightPrivate);
        /* string created_at = 21; */
        if (message.createdAt !== "")
            writer.tag(21, WireType.LengthDelimited).string(message.createdAt);
        /* string updated_at = 22; */
        if (message.updatedAt !== "")
            writer.tag(22, WireType.LengthDelimited).string(message.updatedAt);
        /* optional string uploaded_icon_public_id = 23; */
        if (message.uploadedIconPublicId !== undefined)
            writer.tag(23, WireType.LengthDelimited).string(message.uploadedIconPublicId);
        /* bool enable_sensitive_filter = 24; */
        if (message.enableSensitiveFilter !== false)
            writer.tag(24, WireType.Varint).bool(message.enableSensitiveFilter);
        /* bool enable_global_filter = 25; */
        if (message.enableGlobalFilter !== false)
            writer.tag(25, WireType.Varint).bool(message.enableGlobalFilter);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.UserProfile
 */
export const UserProfile = new UserProfile$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateUserProfileRequest$Type extends MessageType<CreateUserProfileRequest> {
    constructor() {
        super("proto.CreateUserProfileRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "display_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "selected_preset_id", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "icon_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "uploaded_icon", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 20, name: "uploaded_icon_public_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "gender", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "age", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "height", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 9, name: "activity_level", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "current_weight", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 11, name: "target_weight", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 12, name: "show_preset", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 13, name: "pr_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "is_gender_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 15, name: "is_age_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 16, name: "is_height_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 17, name: "is_activity_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 18, name: "is_current_weight_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 19, name: "is_target_weight_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 21, name: "enable_sensitive_filter", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 22, name: "enable_global_filter", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<CreateUserProfileRequest>): CreateUserProfileRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = 0;
        message.displayName = "";
        message.iconType = "";
        message.gender = "";
        message.activityLevel = "";
        message.showPreset = false;
        message.prText = "";
        message.isGenderPrivate = false;
        message.isAgePrivate = false;
        message.isHeightPrivate = false;
        message.isActivityPrivate = false;
        message.isCurrentWeightPrivate = false;
        message.isTargetWeightPrivate = false;
        message.enableSensitiveFilter = false;
        message.enableGlobalFilter = false;
        if (value !== undefined)
            reflectionMergePartial<CreateUserProfileRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateUserProfileRequest): CreateUserProfileRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 user_id */ 1:
                    message.userId = reader.uint32();
                    break;
                case /* string display_name */ 2:
                    message.displayName = reader.string();
                    break;
                case /* optional int32 selected_preset_id */ 3:
                    message.selectedPresetId = reader.int32();
                    break;
                case /* string icon_type */ 4:
                    message.iconType = reader.string();
                    break;
                case /* optional string uploaded_icon */ 5:
                    message.uploadedIcon = reader.string();
                    break;
                case /* optional string uploaded_icon_public_id */ 20:
                    message.uploadedIconPublicId = reader.string();
                    break;
                case /* string gender */ 6:
                    message.gender = reader.string();
                    break;
                case /* optional int32 age */ 7:
                    message.age = reader.int32();
                    break;
                case /* optional double height */ 8:
                    message.height = reader.double();
                    break;
                case /* string activity_level */ 9:
                    message.activityLevel = reader.string();
                    break;
                case /* optional double current_weight */ 10:
                    message.currentWeight = reader.double();
                    break;
                case /* optional double target_weight */ 11:
                    message.targetWeight = reader.double();
                    break;
                case /* bool show_preset */ 12:
                    message.showPreset = reader.bool();
                    break;
                case /* string pr_text */ 13:
                    message.prText = reader.string();
                    break;
                case /* bool is_gender_private */ 14:
                    message.isGenderPrivate = reader.bool();
                    break;
                case /* bool is_age_private */ 15:
                    message.isAgePrivate = reader.bool();
                    break;
                case /* bool is_height_private */ 16:
                    message.isHeightPrivate = reader.bool();
                    break;
                case /* bool is_activity_private */ 17:
                    message.isActivityPrivate = reader.bool();
                    break;
                case /* bool is_current_weight_private */ 18:
                    message.isCurrentWeightPrivate = reader.bool();
                    break;
                case /* bool is_target_weight_private */ 19:
                    message.isTargetWeightPrivate = reader.bool();
                    break;
                case /* bool enable_sensitive_filter */ 21:
                    message.enableSensitiveFilter = reader.bool();
                    break;
                case /* bool enable_global_filter */ 22:
                    message.enableGlobalFilter = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateUserProfileRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 user_id = 1; */
        if (message.userId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.userId);
        /* string display_name = 2; */
        if (message.displayName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.displayName);
        /* optional int32 selected_preset_id = 3; */
        if (message.selectedPresetId !== undefined)
            writer.tag(3, WireType.Varint).int32(message.selectedPresetId);
        /* string icon_type = 4; */
        if (message.iconType !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.iconType);
        /* optional string uploaded_icon = 5; */
        if (message.uploadedIcon !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.uploadedIcon);
        /* string gender = 6; */
        if (message.gender !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.gender);
        /* optional int32 age = 7; */
        if (message.age !== undefined)
            writer.tag(7, WireType.Varint).int32(message.age);
        /* optional double height = 8; */
        if (message.height !== undefined)
            writer.tag(8, WireType.Bit64).double(message.height);
        /* string activity_level = 9; */
        if (message.activityLevel !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.activityLevel);
        /* optional double current_weight = 10; */
        if (message.currentWeight !== undefined)
            writer.tag(10, WireType.Bit64).double(message.currentWeight);
        /* optional double target_weight = 11; */
        if (message.targetWeight !== undefined)
            writer.tag(11, WireType.Bit64).double(message.targetWeight);
        /* bool show_preset = 12; */
        if (message.showPreset !== false)
            writer.tag(12, WireType.Varint).bool(message.showPreset);
        /* string pr_text = 13; */
        if (message.prText !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.prText);
        /* bool is_gender_private = 14; */
        if (message.isGenderPrivate !== false)
            writer.tag(14, WireType.Varint).bool(message.isGenderPrivate);
        /* bool is_age_private = 15; */
        if (message.isAgePrivate !== false)
            writer.tag(15, WireType.Varint).bool(message.isAgePrivate);
        /* bool is_height_private = 16; */
        if (message.isHeightPrivate !== false)
            writer.tag(16, WireType.Varint).bool(message.isHeightPrivate);
        /* bool is_activity_private = 17; */
        if (message.isActivityPrivate !== false)
            writer.tag(17, WireType.Varint).bool(message.isActivityPrivate);
        /* bool is_current_weight_private = 18; */
        if (message.isCurrentWeightPrivate !== false)
            writer.tag(18, WireType.Varint).bool(message.isCurrentWeightPrivate);
        /* bool is_target_weight_private = 19; */
        if (message.isTargetWeightPrivate !== false)
            writer.tag(19, WireType.Varint).bool(message.isTargetWeightPrivate);
        /* optional string uploaded_icon_public_id = 20; */
        if (message.uploadedIconPublicId !== undefined)
            writer.tag(20, WireType.LengthDelimited).string(message.uploadedIconPublicId);
        /* bool enable_sensitive_filter = 21; */
        if (message.enableSensitiveFilter !== false)
            writer.tag(21, WireType.Varint).bool(message.enableSensitiveFilter);
        /* bool enable_global_filter = 22; */
        if (message.enableGlobalFilter !== false)
            writer.tag(22, WireType.Varint).bool(message.enableGlobalFilter);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.CreateUserProfileRequest
 */
export const CreateUserProfileRequest = new CreateUserProfileRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateUserProfileResponse$Type extends MessageType<CreateUserProfileResponse> {
    constructor() {
        super("proto.CreateUserProfileResponse", [
            { no: 1, name: "profile", kind: "message", T: () => UserProfile },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateUserProfileResponse>): CreateUserProfileResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<CreateUserProfileResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateUserProfileResponse): CreateUserProfileResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.UserProfile profile */ 1:
                    message.profile = UserProfile.internalBinaryRead(reader, reader.uint32(), options, message.profile);
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateUserProfileResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.UserProfile profile = 1; */
        if (message.profile)
            UserProfile.internalBinaryWrite(message.profile, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.CreateUserProfileResponse
 */
export const CreateUserProfileResponse = new CreateUserProfileResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserProfileRequest$Type extends MessageType<GetUserProfileRequest> {
    constructor() {
        super("proto.GetUserProfileRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetUserProfileRequest>): GetUserProfileRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = 0;
        if (value !== undefined)
            reflectionMergePartial<GetUserProfileRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetUserProfileRequest): GetUserProfileRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 user_id */ 1:
                    message.userId = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetUserProfileRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 user_id = 1; */
        if (message.userId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.userId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.GetUserProfileRequest
 */
export const GetUserProfileRequest = new GetUserProfileRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserProfileResponse$Type extends MessageType<GetUserProfileResponse> {
    constructor() {
        super("proto.GetUserProfileResponse", [
            { no: 1, name: "profile", kind: "message", T: () => UserProfile },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetUserProfileResponse>): GetUserProfileResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<GetUserProfileResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetUserProfileResponse): GetUserProfileResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.UserProfile profile */ 1:
                    message.profile = UserProfile.internalBinaryRead(reader, reader.uint32(), options, message.profile);
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetUserProfileResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.UserProfile profile = 1; */
        if (message.profile)
            UserProfile.internalBinaryWrite(message.profile, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.GetUserProfileResponse
 */
export const GetUserProfileResponse = new GetUserProfileResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateUserProfileRequest$Type extends MessageType<UpdateUserProfileRequest> {
    constructor() {
        super("proto.UpdateUserProfileRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "display_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "selected_preset_id", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "icon_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "uploaded_icon", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "gender", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "age", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "height", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 9, name: "activity_level", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "current_weight", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 11, name: "target_weight", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 12, name: "show_preset", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 13, name: "pr_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "is_gender_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 15, name: "is_age_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 16, name: "is_height_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 17, name: "is_activity_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 18, name: "is_current_weight_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 19, name: "is_target_weight_private", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 20, name: "enable_sensitive_filter", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateUserProfileRequest>): UpdateUserProfileRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = 0;
        message.displayName = "";
        message.iconType = "";
        message.gender = "";
        message.activityLevel = "";
        message.showPreset = false;
        message.prText = "";
        message.isGenderPrivate = false;
        message.isAgePrivate = false;
        message.isHeightPrivate = false;
        message.isActivityPrivate = false;
        message.isCurrentWeightPrivate = false;
        message.isTargetWeightPrivate = false;
        message.enableSensitiveFilter = false;
        if (value !== undefined)
            reflectionMergePartial<UpdateUserProfileRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateUserProfileRequest): UpdateUserProfileRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 user_id */ 1:
                    message.userId = reader.uint32();
                    break;
                case /* string display_name */ 2:
                    message.displayName = reader.string();
                    break;
                case /* optional int32 selected_preset_id */ 3:
                    message.selectedPresetId = reader.int32();
                    break;
                case /* string icon_type */ 4:
                    message.iconType = reader.string();
                    break;
                case /* optional string uploaded_icon */ 5:
                    message.uploadedIcon = reader.string();
                    break;
                case /* string gender */ 6:
                    message.gender = reader.string();
                    break;
                case /* optional int32 age */ 7:
                    message.age = reader.int32();
                    break;
                case /* optional double height */ 8:
                    message.height = reader.double();
                    break;
                case /* string activity_level */ 9:
                    message.activityLevel = reader.string();
                    break;
                case /* optional double current_weight */ 10:
                    message.currentWeight = reader.double();
                    break;
                case /* optional double target_weight */ 11:
                    message.targetWeight = reader.double();
                    break;
                case /* bool show_preset */ 12:
                    message.showPreset = reader.bool();
                    break;
                case /* string pr_text */ 13:
                    message.prText = reader.string();
                    break;
                case /* bool is_gender_private */ 14:
                    message.isGenderPrivate = reader.bool();
                    break;
                case /* bool is_age_private */ 15:
                    message.isAgePrivate = reader.bool();
                    break;
                case /* bool is_height_private */ 16:
                    message.isHeightPrivate = reader.bool();
                    break;
                case /* bool is_activity_private */ 17:
                    message.isActivityPrivate = reader.bool();
                    break;
                case /* bool is_current_weight_private */ 18:
                    message.isCurrentWeightPrivate = reader.bool();
                    break;
                case /* bool is_target_weight_private */ 19:
                    message.isTargetWeightPrivate = reader.bool();
                    break;
                case /* bool enable_sensitive_filter */ 20:
                    message.enableSensitiveFilter = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateUserProfileRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 user_id = 1; */
        if (message.userId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.userId);
        /* string display_name = 2; */
        if (message.displayName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.displayName);
        /* optional int32 selected_preset_id = 3; */
        if (message.selectedPresetId !== undefined)
            writer.tag(3, WireType.Varint).int32(message.selectedPresetId);
        /* string icon_type = 4; */
        if (message.iconType !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.iconType);
        /* optional string uploaded_icon = 5; */
        if (message.uploadedIcon !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.uploadedIcon);
        /* string gender = 6; */
        if (message.gender !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.gender);
        /* optional int32 age = 7; */
        if (message.age !== undefined)
            writer.tag(7, WireType.Varint).int32(message.age);
        /* optional double height = 8; */
        if (message.height !== undefined)
            writer.tag(8, WireType.Bit64).double(message.height);
        /* string activity_level = 9; */
        if (message.activityLevel !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.activityLevel);
        /* optional double current_weight = 10; */
        if (message.currentWeight !== undefined)
            writer.tag(10, WireType.Bit64).double(message.currentWeight);
        /* optional double target_weight = 11; */
        if (message.targetWeight !== undefined)
            writer.tag(11, WireType.Bit64).double(message.targetWeight);
        /* bool show_preset = 12; */
        if (message.showPreset !== false)
            writer.tag(12, WireType.Varint).bool(message.showPreset);
        /* string pr_text = 13; */
        if (message.prText !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.prText);
        /* bool is_gender_private = 14; */
        if (message.isGenderPrivate !== false)
            writer.tag(14, WireType.Varint).bool(message.isGenderPrivate);
        /* bool is_age_private = 15; */
        if (message.isAgePrivate !== false)
            writer.tag(15, WireType.Varint).bool(message.isAgePrivate);
        /* bool is_height_private = 16; */
        if (message.isHeightPrivate !== false)
            writer.tag(16, WireType.Varint).bool(message.isHeightPrivate);
        /* bool is_activity_private = 17; */
        if (message.isActivityPrivate !== false)
            writer.tag(17, WireType.Varint).bool(message.isActivityPrivate);
        /* bool is_current_weight_private = 18; */
        if (message.isCurrentWeightPrivate !== false)
            writer.tag(18, WireType.Varint).bool(message.isCurrentWeightPrivate);
        /* bool is_target_weight_private = 19; */
        if (message.isTargetWeightPrivate !== false)
            writer.tag(19, WireType.Varint).bool(message.isTargetWeightPrivate);
        /* bool enable_sensitive_filter = 20; */
        if (message.enableSensitiveFilter !== false)
            writer.tag(20, WireType.Varint).bool(message.enableSensitiveFilter);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.UpdateUserProfileRequest
 */
export const UpdateUserProfileRequest = new UpdateUserProfileRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateUserProfileResponse$Type extends MessageType<UpdateUserProfileResponse> {
    constructor() {
        super("proto.UpdateUserProfileResponse", [
            { no: 1, name: "profile", kind: "message", T: () => UserProfile },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateUserProfileResponse>): UpdateUserProfileResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateUserProfileResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateUserProfileResponse): UpdateUserProfileResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.UserProfile profile */ 1:
                    message.profile = UserProfile.internalBinaryRead(reader, reader.uint32(), options, message.profile);
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateUserProfileResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.UserProfile profile = 1; */
        if (message.profile)
            UserProfile.internalBinaryWrite(message.profile, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.UpdateUserProfileResponse
 */
export const UpdateUserProfileResponse = new UpdateUserProfileResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UploadUserIconRequest$Type extends MessageType<UploadUserIconRequest> {
    constructor() {
        super("proto.UploadUserIconRequest", [
            { no: 1, name: "image_data", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "file_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UploadUserIconRequest>): UploadUserIconRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.imageData = new Uint8Array(0);
        message.fileName = "";
        if (value !== undefined)
            reflectionMergePartial<UploadUserIconRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UploadUserIconRequest): UploadUserIconRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes image_data */ 1:
                    message.imageData = reader.bytes();
                    break;
                case /* string file_name */ 2:
                    message.fileName = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UploadUserIconRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes image_data = 1; */
        if (message.imageData.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.imageData);
        /* string file_name = 2; */
        if (message.fileName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.fileName);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.UploadUserIconRequest
 */
export const UploadUserIconRequest = new UploadUserIconRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UploadUserIconResponse$Type extends MessageType<UploadUserIconResponse> {
    constructor() {
        super("proto.UploadUserIconResponse", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "public_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UploadUserIconResponse>): UploadUserIconResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.url = "";
        message.message = "";
        message.publicId = "";
        if (value !== undefined)
            reflectionMergePartial<UploadUserIconResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UploadUserIconResponse): UploadUserIconResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string url */ 1:
                    message.url = reader.string();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* string public_id */ 3:
                    message.publicId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UploadUserIconResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string url = 1; */
        if (message.url !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.url);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* string public_id = 3; */
        if (message.publicId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.publicId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.UploadUserIconResponse
 */
export const UploadUserIconResponse = new UploadUserIconResponse$Type();
