// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "weight_record.proto" (package "weight_record", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message weight_record.WeightRecord
 */
export interface WeightRecord {
    /**
     * @generated from protobuf field: uint32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: uint32 user_id = 2
     */
    userId: number;
    /**
     * @generated from protobuf field: string date = 3
     */
    date: string; // YYYY-MM-DD format
    /**
     * @generated from protobuf field: double weight = 4
     */
    weight: number;
    /**
     * @generated from protobuf field: optional double body_fat = 5
     */
    bodyFat?: number;
    /**
     * @generated from protobuf field: string note = 6
     */
    note: string;
    /**
     * @generated from protobuf field: bool is_public = 7
     */
    isPublic: boolean;
    /**
     * @generated from protobuf field: string created_at = 8
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string updated_at = 9
     */
    updatedAt: string;
}
/**
 * @generated from protobuf message weight_record.CreateWeightRecordRequest
 */
export interface CreateWeightRecordRequest {
    /**
     * @generated from protobuf field: uint32 user_id = 1
     */
    userId: number;
    /**
     * @generated from protobuf field: string date = 2
     */
    date: string; // YYYY-MM-DD format
    /**
     * @generated from protobuf field: double weight = 3
     */
    weight: number;
    /**
     * @generated from protobuf field: optional double body_fat = 4
     */
    bodyFat?: number;
    /**
     * @generated from protobuf field: string note = 5
     */
    note: string;
    /**
     * @generated from protobuf field: bool is_public = 6
     */
    isPublic: boolean;
}
/**
 * @generated from protobuf message weight_record.CreateWeightRecordResponse
 */
export interface CreateWeightRecordResponse {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
    /**
     * @generated from protobuf field: weight_record.WeightRecord record = 2
     */
    record?: WeightRecord;
}
/**
 * @generated from protobuf message weight_record.GetWeightRecordRequest
 */
export interface GetWeightRecordRequest {
    /**
     * @generated from protobuf field: uint32 user_id = 1
     */
    userId: number;
    /**
     * @generated from protobuf field: string date = 2
     */
    date: string; // YYYY-MM-DD format
}
/**
 * @generated from protobuf message weight_record.GetWeightRecordResponse
 */
export interface GetWeightRecordResponse {
    /**
     * @generated from protobuf field: weight_record.WeightRecord record = 1
     */
    record?: WeightRecord;
}
/**
 * @generated from protobuf message weight_record.GetWeightRecordsRequest
 */
export interface GetWeightRecordsRequest {
    /**
     * @generated from protobuf field: uint32 user_id = 1
     */
    userId: number;
    /**
     * @generated from protobuf field: optional string start_date = 2
     */
    startDate?: string; // YYYY-MM-DD format
    /**
     * @generated from protobuf field: optional string end_date = 3
     */
    endDate?: string; // YYYY-MM-DD format
}
/**
 * @generated from protobuf message weight_record.GetWeightRecordsResponse
 */
export interface GetWeightRecordsResponse {
    /**
     * @generated from protobuf field: repeated weight_record.WeightRecord records = 1
     */
    records: WeightRecord[];
}
/**
 * @generated from protobuf message weight_record.UpdateWeightRecordRequest
 */
export interface UpdateWeightRecordRequest {
    /**
     * @generated from protobuf field: uint32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: uint32 user_id = 2
     */
    userId: number;
    /**
     * @generated from protobuf field: string date = 3
     */
    date: string; // YYYY-MM-DD format
    /**
     * @generated from protobuf field: double weight = 4
     */
    weight: number;
    /**
     * @generated from protobuf field: optional double body_fat = 5
     */
    bodyFat?: number;
    /**
     * @generated from protobuf field: string note = 6
     */
    note: string;
    /**
     * @generated from protobuf field: bool is_public = 7
     */
    isPublic: boolean;
}
/**
 * @generated from protobuf message weight_record.UpdateWeightRecordResponse
 */
export interface UpdateWeightRecordResponse {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
    /**
     * @generated from protobuf field: weight_record.WeightRecord record = 2
     */
    record?: WeightRecord;
}
/**
 * @generated from protobuf message weight_record.DeleteWeightRecordRequest
 */
export interface DeleteWeightRecordRequest {
    /**
     * @generated from protobuf field: uint32 id = 1
     */
    id: number;
}
/**
 * @generated from protobuf message weight_record.DeleteWeightRecordResponse
 */
export interface DeleteWeightRecordResponse {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class WeightRecord$Type extends MessageType<WeightRecord> {
    constructor() {
        super("weight_record.WeightRecord", [
            { no: 1, name: "id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "weight", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "body_fat", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "note", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "is_public", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<WeightRecord>): WeightRecord {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.userId = 0;
        message.date = "";
        message.weight = 0;
        message.note = "";
        message.isPublic = false;
        message.createdAt = "";
        message.updatedAt = "";
        if (value !== undefined)
            reflectionMergePartial<WeightRecord>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WeightRecord): WeightRecord {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 id */ 1:
                    message.id = reader.uint32();
                    break;
                case /* uint32 user_id */ 2:
                    message.userId = reader.uint32();
                    break;
                case /* string date */ 3:
                    message.date = reader.string();
                    break;
                case /* double weight */ 4:
                    message.weight = reader.double();
                    break;
                case /* optional double body_fat */ 5:
                    message.bodyFat = reader.double();
                    break;
                case /* string note */ 6:
                    message.note = reader.string();
                    break;
                case /* bool is_public */ 7:
                    message.isPublic = reader.bool();
                    break;
                case /* string created_at */ 8:
                    message.createdAt = reader.string();
                    break;
                case /* string updated_at */ 9:
                    message.updatedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WeightRecord, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).uint32(message.id);
        /* uint32 user_id = 2; */
        if (message.userId !== 0)
            writer.tag(2, WireType.Varint).uint32(message.userId);
        /* string date = 3; */
        if (message.date !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.date);
        /* double weight = 4; */
        if (message.weight !== 0)
            writer.tag(4, WireType.Bit64).double(message.weight);
        /* optional double body_fat = 5; */
        if (message.bodyFat !== undefined)
            writer.tag(5, WireType.Bit64).double(message.bodyFat);
        /* string note = 6; */
        if (message.note !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.note);
        /* bool is_public = 7; */
        if (message.isPublic !== false)
            writer.tag(7, WireType.Varint).bool(message.isPublic);
        /* string created_at = 8; */
        if (message.createdAt !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.createdAt);
        /* string updated_at = 9; */
        if (message.updatedAt !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.updatedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message weight_record.WeightRecord
 */
export const WeightRecord = new WeightRecord$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateWeightRecordRequest$Type extends MessageType<CreateWeightRecordRequest> {
    constructor() {
        super("weight_record.CreateWeightRecordRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "weight", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "body_fat", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "note", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "is_public", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<CreateWeightRecordRequest>): CreateWeightRecordRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = 0;
        message.date = "";
        message.weight = 0;
        message.note = "";
        message.isPublic = false;
        if (value !== undefined)
            reflectionMergePartial<CreateWeightRecordRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateWeightRecordRequest): CreateWeightRecordRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 user_id */ 1:
                    message.userId = reader.uint32();
                    break;
                case /* string date */ 2:
                    message.date = reader.string();
                    break;
                case /* double weight */ 3:
                    message.weight = reader.double();
                    break;
                case /* optional double body_fat */ 4:
                    message.bodyFat = reader.double();
                    break;
                case /* string note */ 5:
                    message.note = reader.string();
                    break;
                case /* bool is_public */ 6:
                    message.isPublic = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateWeightRecordRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 user_id = 1; */
        if (message.userId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.userId);
        /* string date = 2; */
        if (message.date !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.date);
        /* double weight = 3; */
        if (message.weight !== 0)
            writer.tag(3, WireType.Bit64).double(message.weight);
        /* optional double body_fat = 4; */
        if (message.bodyFat !== undefined)
            writer.tag(4, WireType.Bit64).double(message.bodyFat);
        /* string note = 5; */
        if (message.note !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.note);
        /* bool is_public = 6; */
        if (message.isPublic !== false)
            writer.tag(6, WireType.Varint).bool(message.isPublic);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message weight_record.CreateWeightRecordRequest
 */
export const CreateWeightRecordRequest = new CreateWeightRecordRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateWeightRecordResponse$Type extends MessageType<CreateWeightRecordResponse> {
    constructor() {
        super("weight_record.CreateWeightRecordResponse", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "record", kind: "message", T: () => WeightRecord }
        ]);
    }
    create(value?: PartialMessage<CreateWeightRecordResponse>): CreateWeightRecordResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<CreateWeightRecordResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateWeightRecordResponse): CreateWeightRecordResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                case /* weight_record.WeightRecord record */ 2:
                    message.record = WeightRecord.internalBinaryRead(reader, reader.uint32(), options, message.record);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateWeightRecordResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        /* weight_record.WeightRecord record = 2; */
        if (message.record)
            WeightRecord.internalBinaryWrite(message.record, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message weight_record.CreateWeightRecordResponse
 */
export const CreateWeightRecordResponse = new CreateWeightRecordResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetWeightRecordRequest$Type extends MessageType<GetWeightRecordRequest> {
    constructor() {
        super("weight_record.GetWeightRecordRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "date", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetWeightRecordRequest>): GetWeightRecordRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = 0;
        message.date = "";
        if (value !== undefined)
            reflectionMergePartial<GetWeightRecordRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetWeightRecordRequest): GetWeightRecordRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 user_id */ 1:
                    message.userId = reader.uint32();
                    break;
                case /* string date */ 2:
                    message.date = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetWeightRecordRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 user_id = 1; */
        if (message.userId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.userId);
        /* string date = 2; */
        if (message.date !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.date);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message weight_record.GetWeightRecordRequest
 */
export const GetWeightRecordRequest = new GetWeightRecordRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetWeightRecordResponse$Type extends MessageType<GetWeightRecordResponse> {
    constructor() {
        super("weight_record.GetWeightRecordResponse", [
            { no: 1, name: "record", kind: "message", T: () => WeightRecord }
        ]);
    }
    create(value?: PartialMessage<GetWeightRecordResponse>): GetWeightRecordResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetWeightRecordResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetWeightRecordResponse): GetWeightRecordResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* weight_record.WeightRecord record */ 1:
                    message.record = WeightRecord.internalBinaryRead(reader, reader.uint32(), options, message.record);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetWeightRecordResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* weight_record.WeightRecord record = 1; */
        if (message.record)
            WeightRecord.internalBinaryWrite(message.record, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message weight_record.GetWeightRecordResponse
 */
export const GetWeightRecordResponse = new GetWeightRecordResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetWeightRecordsRequest$Type extends MessageType<GetWeightRecordsRequest> {
    constructor() {
        super("weight_record.GetWeightRecordsRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "start_date", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "end_date", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetWeightRecordsRequest>): GetWeightRecordsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = 0;
        if (value !== undefined)
            reflectionMergePartial<GetWeightRecordsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetWeightRecordsRequest): GetWeightRecordsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 user_id */ 1:
                    message.userId = reader.uint32();
                    break;
                case /* optional string start_date */ 2:
                    message.startDate = reader.string();
                    break;
                case /* optional string end_date */ 3:
                    message.endDate = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetWeightRecordsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 user_id = 1; */
        if (message.userId !== 0)
            writer.tag(1, WireType.Varint).uint32(message.userId);
        /* optional string start_date = 2; */
        if (message.startDate !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.startDate);
        /* optional string end_date = 3; */
        if (message.endDate !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.endDate);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message weight_record.GetWeightRecordsRequest
 */
export const GetWeightRecordsRequest = new GetWeightRecordsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetWeightRecordsResponse$Type extends MessageType<GetWeightRecordsResponse> {
    constructor() {
        super("weight_record.GetWeightRecordsResponse", [
            { no: 1, name: "records", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => WeightRecord }
        ]);
    }
    create(value?: PartialMessage<GetWeightRecordsResponse>): GetWeightRecordsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.records = [];
        if (value !== undefined)
            reflectionMergePartial<GetWeightRecordsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetWeightRecordsResponse): GetWeightRecordsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated weight_record.WeightRecord records */ 1:
                    message.records.push(WeightRecord.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetWeightRecordsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated weight_record.WeightRecord records = 1; */
        for (let i = 0; i < message.records.length; i++)
            WeightRecord.internalBinaryWrite(message.records[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message weight_record.GetWeightRecordsResponse
 */
export const GetWeightRecordsResponse = new GetWeightRecordsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateWeightRecordRequest$Type extends MessageType<UpdateWeightRecordRequest> {
    constructor() {
        super("weight_record.UpdateWeightRecordRequest", [
            { no: 1, name: "id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "weight", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "body_fat", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "note", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "is_public", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateWeightRecordRequest>): UpdateWeightRecordRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.userId = 0;
        message.date = "";
        message.weight = 0;
        message.note = "";
        message.isPublic = false;
        if (value !== undefined)
            reflectionMergePartial<UpdateWeightRecordRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateWeightRecordRequest): UpdateWeightRecordRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 id */ 1:
                    message.id = reader.uint32();
                    break;
                case /* uint32 user_id */ 2:
                    message.userId = reader.uint32();
                    break;
                case /* string date */ 3:
                    message.date = reader.string();
                    break;
                case /* double weight */ 4:
                    message.weight = reader.double();
                    break;
                case /* optional double body_fat */ 5:
                    message.bodyFat = reader.double();
                    break;
                case /* string note */ 6:
                    message.note = reader.string();
                    break;
                case /* bool is_public */ 7:
                    message.isPublic = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateWeightRecordRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).uint32(message.id);
        /* uint32 user_id = 2; */
        if (message.userId !== 0)
            writer.tag(2, WireType.Varint).uint32(message.userId);
        /* string date = 3; */
        if (message.date !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.date);
        /* double weight = 4; */
        if (message.weight !== 0)
            writer.tag(4, WireType.Bit64).double(message.weight);
        /* optional double body_fat = 5; */
        if (message.bodyFat !== undefined)
            writer.tag(5, WireType.Bit64).double(message.bodyFat);
        /* string note = 6; */
        if (message.note !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.note);
        /* bool is_public = 7; */
        if (message.isPublic !== false)
            writer.tag(7, WireType.Varint).bool(message.isPublic);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message weight_record.UpdateWeightRecordRequest
 */
export const UpdateWeightRecordRequest = new UpdateWeightRecordRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateWeightRecordResponse$Type extends MessageType<UpdateWeightRecordResponse> {
    constructor() {
        super("weight_record.UpdateWeightRecordResponse", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "record", kind: "message", T: () => WeightRecord }
        ]);
    }
    create(value?: PartialMessage<UpdateWeightRecordResponse>): UpdateWeightRecordResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateWeightRecordResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateWeightRecordResponse): UpdateWeightRecordResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                case /* weight_record.WeightRecord record */ 2:
                    message.record = WeightRecord.internalBinaryRead(reader, reader.uint32(), options, message.record);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateWeightRecordResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        /* weight_record.WeightRecord record = 2; */
        if (message.record)
            WeightRecord.internalBinaryWrite(message.record, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message weight_record.UpdateWeightRecordResponse
 */
export const UpdateWeightRecordResponse = new UpdateWeightRecordResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteWeightRecordRequest$Type extends MessageType<DeleteWeightRecordRequest> {
    constructor() {
        super("weight_record.DeleteWeightRecordRequest", [
            { no: 1, name: "id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteWeightRecordRequest>): DeleteWeightRecordRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        if (value !== undefined)
            reflectionMergePartial<DeleteWeightRecordRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteWeightRecordRequest): DeleteWeightRecordRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 id */ 1:
                    message.id = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteWeightRecordRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).uint32(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message weight_record.DeleteWeightRecordRequest
 */
export const DeleteWeightRecordRequest = new DeleteWeightRecordRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteWeightRecordResponse$Type extends MessageType<DeleteWeightRecordResponse> {
    constructor() {
        super("weight_record.DeleteWeightRecordResponse", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteWeightRecordResponse>): DeleteWeightRecordResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteWeightRecordResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteWeightRecordResponse): DeleteWeightRecordResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteWeightRecordResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message weight_record.DeleteWeightRecordResponse
 */
export const DeleteWeightRecordResponse = new DeleteWeightRecordResponse$Type();
